#!/bin/bash

#scrcpy-r Remote scrcpy simplified version 1.0
#This is a simplified and customized scrcpy to apply tcpip more easily, using adb over tcpip to remote control an android phone on linux - Scripted by Sensy
# The Phone MUST initially be plugged in with ADB mode enabled

echo ""
echo "scrcpy-r by Sensy --VERSION 1.0"
echo "This is a simplified and customized scrcpy to apply tcpip more easily, using adb over tcpip to remote control an android phone on linux."
echo "Scripted by Sensy"



echo ""
echo "USAGE"
echo "scrcpy-r [ip address]"
echo ""

echo "INSTRUCTIONS"
echo "Please ensure that the following conditions are all met:"
echo "1. The android phone is connected via USB to the pc"
echo "2. Debugging mode is activated in the android"
echo "3. ADB is installed on ubuntu"
echo "4. scrcpy is installed on ubuntu"
echo "5. The phone and the laptop are connected on the same network"

adb devices
adb tcpip 5500
adb connect $1:5500
scrcpy